name: rse-graph
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - ca-certificates=2019.11.27=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py36_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_1000
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - importlib_metadata=1.3.0=py36_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipython=7.11.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py36_0
  - jpeg=9b=h024ee3a_2
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter_client=5.3.4=py36_0
  - jupyter_core=4.6.1=py36_0
  - jupyterlab=1.2.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py36h516909a_0
  - mistune=0.8.4=py36h516909a_1000
  - more-itertools=8.0.2=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.3=py_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.1=py36_0
  - openssl=1.1.1d=h7b6447c_3
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h049681c_0
  - parso=0.5.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.5.2=py_0
  - pyrsistent=0.15.7=py36h516909a_0
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py36h1768529_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py_0
  - setuptools=44.0.0=py36_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h516909a_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - click==7.0
    - flask==1.0.2
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - lxml==4.3.3
    - natsort==6.0.0
    - pygraphviz==1.5
    - pyparsing==2.4.0
    - urllib3==1.25.2
    - werkzeug==0.16.0

